### ISSUE TITLE
Yarn Install Fail on Linux Ubuntu 16

### ISSUE THREAD

**Issue by aacostarua** [Uniswap/uniswap-frontend#222]
Followed the instructions provided on github & readme correctly:
sudo yarn
yarn install v1.13.0
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/4] ⠄ waiting...
[2/4] ⠄ sha3
[3/4] ⡀ websocket
error /home/user1/Desktop/uniswap-frontend-master/node_modules/sha3: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/user1/Desktop/uniswap-frontend-master/node_modules/sha3
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.14.2 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user1/Desktop/uniswap-frontend-master/node_modules/sha3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user1/.node-gyp/10.14.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/user1/.node-gyp/10.14.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/user1/.node-gyp/10.14.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/user1/Desktop/uniswap-frontend-master/node_modules/sha3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/user1/Desktop/uniswap-frontend-master/node_modules/sha3/build'
  CXX(target) Release/obj.target/sha3/src/addon.o
In file included from ../src/addon.cpp:4:0:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:840:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, func, argc, argv);
                                                            ^
In file included from ../src/addon.cpp:1:0:
/home/user1/.node-gyp/10.14.2/include/node/node.h:177:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/user1/.node-gyp/10.14.2/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from ../src/addon.cpp:4:0:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:855:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
                                                              ^
In file included from ../src/addon.cpp:1:0:
/home/user1/.node-gyp/10.14.2/include/node/node.h:170:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/user1/.node-gyp/10.14.2/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from ../src/addon.cpp:4:0:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:870:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, method, argc, argv);
                                                              ^
In file included from ../src/addon.cpp:1:0:
/home/user1/.node-gyp/10.14.2/include/node/node.h:163:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/user1/.node-gyp/10.14.2/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from ../src/addon.cpp:4:0:
../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’:
../../nan/nan.h:1484:5: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
     ));
     ^
In file included from ../src/addon.cpp:1:0:
/home/user1/.node-gyp/10.14.2/include/node/node.h:177:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/user1/.node-gyp/10.14.2/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
../src/addon.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE SHA3Hash::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/addon.cpp:36:64: warning: ‘int32_t v8::Value::Int32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   hashlen = info[0]->IsUndefined() ? 512 : info[0]->Int32Value();
                                                                ^
In file included from /home/user1/.node-gyp/10.14.2/include/node/v8.h:26:0,
                 from /home/user1/.node-gyp/10.14.2/include/node/node.h:63,
                 from ../src/addon.cpp:1:
/home/user1/.node-gyp/10.14.2/include/node/v8.h:2478:46: note: declared here
   V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
                                              ^
/home/user1/.node-gyp/10.14.2/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/addon.cpp:59:58: error: no matching function for call to ‘v8::Function::NewInstance(const int&, v8::Local<v8::Value> [1])’
    info.GetReturnValue().Set(cons->NewInstance(argc, argv));
                                                          ^
In file included from /home/user1/.node-gyp/10.14.2/include/node/node.h:63:0,
                 from ../src/addon.cpp:1:
/home/user1/.node-gyp/10.14.2/include/node/v8.h:3993:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^
/home/user1/.node-gyp/10.14.2/include/node/v8.h:3993:44: note:   candidate expects 3 arguments, 2 provided
/home/user1/.node-gyp/10.14.2/include/node/v8.h:3996:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^
/home/user1/.node-gyp/10.14.2/include/node/v8.h:3996:44: note:   candidate expects 1 argument, 2 provided
../src/addon.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE SHA3Hash::Update(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/addon.cpp:97:49: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
    Local<Object> buffer_obj = info[0]->ToObject();
                                                 ^
In file included from /home/user1/.node-gyp/10.14.2/include/node/node.h:63:0,
                 from ../src/addon.cpp:1:
/home/user1/.node-gyp/10.14.2/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^
sha3.target.mk:105: recipe for target 'Release/obj.target/sha3/src/addon.o' failed
make: *** [Release/obj.target/sha3/src/addon.o] Error 1
make: Leaving directory '/home/user1/Desktop/uniswap-frontend-master/node_modules/sha3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.4.0-141-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user1/Desktop/uniswap-frontend-master/node_modules/sha3
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.8.0

**Comment by Anish-Agnihotri** [comment]
Hey! 

This is a problem with newer Node versions that has been acknowledged by the developer of the npm module. Try downgrading to a stable release of node 8.x and it should work again.

It's easiest if you use something like nvm (node version manager) so that you can easily switch installed node versions, but manual install works just fine. Let me know if you need any help.

[Here](streamable.com/fv1y7) is an example of me compiling on v10 (with errors) and then switching to v8 and compiling with no errors.

Cheers!

Anish

**Comment by aacostarua** [comment]
@Anish-Agnihotri Hey, thanks a lot for the response.  I will try that.  One other question, how do you know how to compile the src folder into the project.  Is it a 'make install' command? Thanks.

**Comment by Anish-Agnihotri** [comment]
As far as my understanding goes, since this is a React project, there isn't a need to compile the src folder.

After you run `yarn` all the dependencies are installed, and then running `yarn start:rinkeby` should automatically render the files in the src folder.

So, no need to compile the src folder. React handles everything for you.

**Comment by aacostarua** [comment]
@Anish-Agnihotri One other question, I got my ERC20 contracts on the exchange list (pointing to the same deployed exchange address now, do I need to re-deploy exchange contract for every token or one for all?) How do I set the conversion rate from token to token.  Im just looking for a standard 1:1 ration for now.  Thanks.

**Comment by Anish-Agnihotri** [comment]
1. The contracts for the exchanges don't need to be re-deployed if you're testing ones that are already on a testnet. If you want to add a new ERC20 token though, you'd have to deploy the token contract and then add it to the exchange.
2. The conversion rate is set by the pool (through adding liquidity). I don't think you can set the exchange rate for a contract already in use by Uniswap, since these probably already have funds in the pool that dictate the pricing. You can though setup a new ERC20 token (using something like a [Token Generator](https://vittominacori.github.io/erc20-generator/)), deploy it to the test net, and then add pool liquidity to this token at a 1:1 rate, allowing you to theoretically set the price.

I'm not an expert on this though, so if something doesn't work out, I know the [Uniswap Slack](https://uni-swap.slack.com) is a great place to ask a question! And, of course, do let me know if you need any clarification on something and I'd be happy to record an example of me doing it and send it your way.

**Comment by aacostarua** [comment]
@Anish-Agnihotri What about in the case of a private network how would I set liquidity then.  Both coins are on my network too.

**Comment by haydenadams** [comment]
@aacostarua So you are running a private EVM fork with no native currency?

**Comment by aacostarua** [comment]
Yes, exactly.  I was wondering if you could just the liquidity between the ERC20's?

**Comment by haydenadams** [comment]
And a smaller frontend rework

**Comment by aacostarua** [comment]
Gotcha but I could just set the contracts equal to 1 ETH each then exchange the coins directly though right?

**Comment by haydenadams** [comment]
I don't know how your fork works so idk exactly how to answer your question.

Right now, on Ethereum, ETH is a fundamentally necessary part of Uniswap on a smart contract level. On Ethereum, it is currently impossible to use the smart contracts without depositing ETH. 

This can be changed but requires a deeper understanding of the smart contracts.

**Comment by aacostarua** [comment]
Gotcha I get that. There is “ETH” on my network. I would just have to set the ERC20 contracts equal to 1 ETH. I order to exchange the coins. That was my last question.

**Comment by haydenadams** [comment]
Oh yeah you have to deposit an equivalent value of ETH and ERC20 tokens into the exchange using addLiquidity function. Which means your ETH will have to have some value.

**Comment by aacostarua** [comment]
Nice thanks for the info. Except it’s saying my token already has a value to ETH is there a way to clear this exchange value?  Also I’m curious as to where you can set the token image for a contract.  Thanks

**Comment by haydenadams** [comment]
If you already added eth you can change the value by making trades. Have you read through the whitepaper and project documentation yet? These links might help answer a lot of your questions:

https://medium.com/@cyrus.younessi/uniswap-a-unique-exchange-f4ef44f807bf

https://docs.uniswap.io

https://hackmd.io/C-DvwDSfSxuh-Gd4WKE_ig

**Comment by aacostarua** [comment]
Thanks for the references, yeh I’ve looked at them now. Question though, it keeps defaulting to this when I try to add Liquidity : Exchange Rate
1 ETH = 33333332.2926 APR
Current Pool Size30000.00 ETH+ 999999968777.86<tel:+%20999999968777.86>APR
Your Pool Share (NaN%)NaN ETH + NaN APR
Hide Details[https://ci6.googleusercontent.com/proxy/wBjIaerBmbG5U279nZWbAAH5caFh_W3R12Lpc3FAdt1rrXb8GWzpNf1XPwaI9sLCluDlpyo6GyMWXqi-iUeh-heG4ZPzv_4ZfA8I9FV227WS5UbGhVsZIQ=s0-d-e1-ft#http://bc3.mycryptobox.com:3000/static/media/dropup-blue.b96d70e1.svg]
You are adding between 0.1 ETH and 3249999.898528 - 3416666.559991 APR into the liquidity pool.
You will mint 0 liquidity tokens.
Current total supply of liquidity tokens is 0
At current exchange rate, each pool token is worth Infinity ETH and Infinity APR. won’t let me set the level

**Comment by aacostarua** [comment]
What do I have to do to properly set the liquidity, do I have create the exchange through the interface instead of deploying the exchange contract through the bytecode and pointing it manually ? @Anish-Agnihotri   Thanks.
